<x-layout>
    <div id="con" class="hidden">
    </div>
    <div class="container grid grid-cols-2 mx-auto bg-floral-white rounded-xl  w-full h-[600px] p-10">
        <div class=" h-[500px] bg-gray-500 mr-20" > <!--Картинка--></div>
            <div class="h-full overflow-x-auto ">
                <h1 class="text-4xl mb-20">Название</h1>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Delectus dicta asperiores dolorem! Assumenda a dignissimos possimus, ad atque, eligendi officiis illum impedit libero commodi quo, delectus voluptatum! Enim, dicta totam Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas qui exercitationem debitis sint deleniti harum beatae quasi similique recusandae soluta unde accusamus modi, consequatur reiciendis. Velit, reiciendis quo. Temporibus, vero. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis sed itaque voluptatibus, adipisci nostrum quisquam alias eum distinctio iure in provident officiis rem natus commodi officia blanditiis modi. Fuga, reiciendis. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis fuga, quos delectus, veniam eum, placeat modi nihil tenetur aliquam molestiae autem sunt unde quas dolores eius impedit voluptatibus aspernatur cum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi ipsam quas iusto amet est necessitatibus architecto, eum libero voluptatum distinctio iure adipisci odit voluptates. Adipisci aut deserunt facilis quae ad? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae voluptatum nam magnam recusandae voluptate distinctio animi temporibus deleniti placeat architecto, repellat, aut facilis dolores necessitatibus iure itaque. Temporibus, repellat culpa! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error magnam a soluta repellat. Repudiandae possimus esse porro, illo facilis veritatis asperiores quibusdam aut atque vitae excepturi, numquam blanditiis optio doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe asperiores recusandae expedita quod quae pariatur sed, facere, eveniet voluptatum molestiae veritatis! Vero doloribus iure nisi! Laudantium culpa non nostrum numquam.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Delectus dicta asperiores dolorem! Assumenda a dignissimos possimus, ad atque, eligendi officiis illum impedit libero commodi quo, delectus voluptatum! Enim, dicta totam Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas qui exercitationem debitis sint deleniti harum beatae quasi similique recusandae soluta unde accusamus modi, consequatur reiciendis. Velit, reiciendis quo. Temporibus, vero. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reiciendis sed itaque voluptatibus, adipisci nostrum quisquam alias eum distinctio iure in provident officiis rem natus commodi officia blanditiis modi. Fuga, reiciendis. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Blanditiis fuga, quos delectus, veniam eum, placeat modi nihil tenetur aliquam molestiae autem sunt unde quas dolores eius impedit voluptatibus aspernatur cum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi ipsam quas iusto amet est necessitatibus architecto, eum libero voluptatum distinctio iure adipisci odit voluptates. Adipisci aut deserunt facilis quae ad? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae voluptatum nam magnam recusandae voluptate distinctio animi temporibus deleniti placeat architecto, repellat, aut facilis dolores necessitatibus iure itaque. Temporibus, repellat culpa! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error magnam a soluta repellat. Repudiandae possimus esse porro, illo facilis veritatis asperiores quibusdam aut atque vitae excepturi, numquam blanditiis optio doloremque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe asperiores recusandae expedita quod quae pariatur sed, facere, eveniet voluptatum molestiae veritatis! Vero doloribus iure nisi! Laudantium culpa non nostrum numquam.
                </p>
            </div>
    </div>
</x-layout>
